vimrc: delete colorscheme.
error: No such scheme 'gruvbox'

because of change install method: curl to Plugin install.

Signed-off-by: steve.jeong <jkhpro1003@gmail.com>